hq_hotel_mart/urls.py
from django.conf.urls import url

from . import views


app_name = 'hq_hotel_mart'
urlpatterns = [
      url( r'^currency/(?P<pk>\d+)/'
         , views.CurrencyView.as_view()
         , name='currency'
         )
    , url( r'^currency/$'
         , views.CurrencyListView.as_view()
         , name='currency_list'
         )
    , url( r'^offer/(?P<pk>\d+)/'
         , views.OfferView.as_view()
         , name='offer'
         )
    , url( r'^offer/$'
         , views.OfferListView.as_view()
         , name='offer_list'
         )
    , url( r'^hour/(?P<pk>\d+)/'
         , views.HourView.as_view()
         , name='hour'
         )
    , url( r'^hour/$'
         , views.HourListView.as_view()
         , name='hour_list'
         )
    , url( r'^hotel/(?P<pk>\d+)/'
         , views.HotelOfferView.as_view()
         , name='hotel'
         )
    , url( r'^hotel/$'
         , views.HotelOfferListView.as_view()
         , name='hotel_list'
         )
    , url( r'^api/$'
         , views.ApiView.as_view()
         , name='api'
         )
    , url( r''
         , views.DocView.as_view()
         , name='doc'
         )
]

hq_hotel_mart/templates/hq_hotel_mart/currency.html
{% extends "hq_main/hq.html" %}

{% block title %}
{{ currency.code }} - {{ currency.name }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<div>Name: {{ currency.name }}</div>
<div>ISO Code: {{ currency.code }}</div>
{% endblock %}

hq_hotel_mart/templates/hq_hotel_mart/doc.html
{% extends "hq_main/hq.html" %}

{% block title %}
HQ Hotel Mart
{% endblock %}

{% block page_body %}
{{ block.super }}

<h1>HQ Hotel Mart</h1>

<h3>Available commands</h3>

<p>
To configure the data mart use the following commands.
</p>

<pre>
hqm-pop-hours [-hvt] -y <4 digit year>

  -h  Print usage.
  -v  Be verbose, print successes as well as errors.
  -t  Truncate the hour table before inserting.
  -y  A four digit year (e.g. 2016) to load the hour table with.
</pre>

<p>
Populates all hours for a given year.  The mart will only load offers that can
be used within these hours.  This allows for easy reload of the entire mart
from time to time, by truncating the tables and reloading hours and offers.
</p>

<pre>
hqm-reload [-hvt]

  -h  Print usage.
  -v  Be verbose, print successes as well as errors.
  -t  Truncate the currency, offer and hoteloffer tables before beginning
      the insert, this is useful to reload the mart from scratch.
</pre>

<p>
Loads the offers from the warehouse and inserts into the caches by hour.  The
caches can then be queried from the API.
</p>

<h3>API</h3>

<p>
  <code>GET</code> from <code>{% url 'hq_hotel_mart:api' %}</code>
</p>

<p>Examples</p>

<p>When the API is able to find an offer:</p>

<pre>
GET {% url 'hq_hotel_mart:api' %}?queryAt=2016-06-07T09&hotelId=169&checkinDate=2016-06-09&checkoutDate=2016-06-10 HTTP/1.1
Host: ...

...

HTTP/1.1 200 OK

{ offerId: 12345678
, hotelId: 169
, checkinDate: '2016-06-09'
, checkoutDate: '2016-06-10'
, sellingPrice: 650.0
, currencyCode: 'HKD'
}
</pre>

<p>When no offer exist return a fixed price:</p>

<pre>
GET {% url 'hq_hotel_mart:api' %}?queryAt=2016-06-07T09&hotelId=169&checkinDate=2016-06-09&checkoutDate=2016-06-12 HTTP/1.1
Host: ...

...

HTTP/1.1 200 OK

{ hotelId: 169
, checkinDate: '2016-06-09'
, checkoutDate: '2016-06-12'
, sellingPrice: 300.0
, currencyCode: 'USD'
}
</pre>

{% endblock %}

hq_hotel_mart/templates/hq_hotel_mart/hotel_offer.html
{% extends "hq_main/hq.html" %}

{% block title %}
{{ hotel_offer.hotel_id }} - {{ hotel_offer.offer_id }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<div>Hotel: {{ hotel_offer.hotel_id }}</div>
<div>Offer: {{ hotel_offer.offer_id}}</div>
<div>Days: {{ hotel_offer.days}}</div>
<div>Hour: {{ hotel_offer.hour }}</div>
{% endblock %}

hq_hotel_mart/templates/hq_hotel_mart/hour.html
{% extends "hq_main/hq.html" %}

{% block title %}
{{ hour.day|date:'Y-m-d' }} - {{ hour.hour|stringformat:"02i" }}:00:00
{% endblock %}

{% block page_body %}
{{ block.super }}

<div>Day: {{ hour.day|date:'Y-m-d' }}</div>
<div>Hour: {{ hour.hour|stringformat:"02i" }}:00:00</div>
{% endblock %}

hq_hotel_mart/templates/hq_hotel_mart/offer.html
{% extends "hq_main/hq.html" %}

{% block title %}
{{ offer.hotel_id }} - {{ offer.price_usd|floatformat:2 }}
{% endblock %}

{% block page_body %}
{{ block.super }}

<div>Hotel: {{ offer.hotel_id }}</div>
<div>
  Price:
  {{ offer.price_usd }} USD
  OR
  {{ offer.original_price}} {{ offer.original_currency.code }}
</div>
<div>Breakfast included:
  {% if offer.breakfast_included %}
    Yes
  {% else %}
    No
  {% endif %}
</div>
<div>Check-in: {{ offer.checkin_date|date:'M d, Y' }}</div>
<div>Check-out: {{ offer.checkout_date|date:'M d, Y' }}</div>
<div>
  Offer valid from:
  {{ offer.valid_from_date|date:'M d, Y' }}
  at
  {{ offer.valid_from_time|time:'H:i:s' }}
</div>
<div>
  Offer valid until:
  {{ offer.valid_to_date|date:'M d, Y' }}
  at
  {{ offer.valid_to_time|time:'H:i:s' }}
</div>
{% endblock %}